config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users

  resources :users do
    member do
      put :follow
      put :unfollow
    end
  end

  resources :outfits do
    # /outfits/pending
    collection do
      get :pending
    end

    # /outfits/:id/pending
    member do
      put :status
      post :add_comment
      delete :delete_comment
    end
  end
  resources :accessories
  resources :shoes
  resources :garments

  get 'random', to: 'outfits#random', as: 'random_outfit'
  # post 'seasonal', to: 'outfits#seasonal', as: 'seasonal_outfit'
  get 'help'    => 'home#help'
  get 'about'   => 'home#about'
  get 'contact' => 'hlome#contact'

  get 'delete/:id' => 'garments#destroy', as: 'garment_destroy'
  get 'delete_accessories/:id' => 'accessories#destroy', as: 'accessory_delete'
  get 'delete_shoes/:id' => 'shoes#destroy', as: 'shoes_delete'
end

app/models/outfit.rb
class Outfit < ActiveRecord::Base
  validates :user_id, :garment_id, :shoe_id, :accessory_id, presence: true

  belongs_to :garment
  belongs_to :accessory
  belongs_to :shoe
  belongs_to :user
  mount_uploader :image, ImageUploader

  attr_accessor :image_cache

  validates_uniqueness_of(
    :user_id,
    scope: [:garment_id, :accessory_id, :shoe_id],
    message: 'This combination is saved already for the current user.'
  )

  enum action: [:pending, :approve, :reject]

  acts_as_commentable

  # ActiveRecord:Enum default is 0 (pending) set in migration
  # user selects 1 for approve, 2 for reject

  def self.random_accessory
    random_accessory_id = Accessory.pluck(:id).sample
    # we're using pluck because we want an array w available accessory ids
    # then sample because we want just 1
    Accessory.find(random_accessory_id)
  end

  def self.random_garment
    random_garment_id = Garment.pluck(:id).sample
    Garment.find(random_garment_id)
end

  def self.random_shoe
    random_shoe_id = Shoe.pluck(:id).sample
    Shoe.find(random_shoe_id)
  end

  def self.get_seasonal_outfit(current_user_temp)
     if current_user_temp <= 32 # winter
        [Accessory.where(season: 1).sample, Garment.where(season: 1).sample, Shoe.where(season: 1).sample]
      elsif  current_user_temp > 33 && current_user_temp < 55 # 2
        [Accessory.where(season: 2).sample, Garment.where(season: 2).sample, Shoe.where(season: 2).sample]
      elsif  current_user_temp >= 55 && current_user_temp <= 70 # 2
       [Accessory.where(season: 3).sample, Garment.where(season: 3).sample, Shoe.where(season: 3).sample]
      else
        [Accessory.where(season: 4).sample, Garment.where(season: 4).sample, Shoe.where(season: 4).sample]
    end
end

end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  # outfits last only while they are on-screen should be created and shown but not saved.

  def new
    @outfit = Outfit.new
  end

   def destroy
    @outfit = Outfit.find(params[:id])
    puts "@outfit: #{@outfit.inspect}"
    @outfit.destroy
    flash[:success] = "Let's find you another outfit."
    render 'new'
  end

  def show
    @outfit = Outfit.find(params[:id])
  end

  def random
    @random_accessory = Accessory.random_accessory(current_user.id)
    @random_garment = Garment.random_garment(current_user.id)
    @random_shoe = Shoe.random_shoe(current_user.id)
    puts "@random_accessory: #{@random_accessory.inspect}"
    puts "@random_shoe: #{@random_shoe.inspect}"
    puts "@random_garment: #{@random_garment.inspect}"
  end

  # def seasonal
  #   puts @temperature.inspect
  #   puts "seasonal outfit!"
  #   @seasonal_accessory = Outfit.get_seasonal_outfit(@temperature)[0]
  #   @seasonal_garment = Outfit.get_seasonal_outfit(@temperature)[1]
  #   @seasonal_shoe = Outfit.get_seasonal_outfit(@temperature)[2]
  # end

  def create
    @outfit = Outfit.new(outfits_params)
    @outfit.user_id = current_user.id
    if @outfit.save
      flash[:success] = 'Get dressed, not stressed!'
      redirect_to @outfit
    else
      flash[:error] = @outfit.errors.full_messages.join("\n")
      render 'new'
    end
  end

  def index
    # if params[:other_user_id].present?
    #   @outfits = Outfit.where(user_id: params[:other_user_id], action: 1)
    # #@outfits.map{|o| o.comments.new}
    # else
    #   @outfits = Outfit.where(user_id: current_user.id, action: 1)
    # end
    @outfits = Outfit.where(user_id: current_user.id)

  end

  def add_comment
    @outfit = Outfit.find(params[:id])
    comment = @outfit.comments.new
    comment.comment = params[:comment][:comment]
    comment.user_id = current_user.id
    comment.save
    redirect_to :back
  end  


  def delete_comment
    @outfit = Outfit.find(params[:id])
    @comment= @outfit.comments.where(id: params[:comment_id]).first
    @comment.destroy
    redirect_to :back
  end

  def pending 
    @outfits = Outfit.where(user_id: current_user.id, action: 0)
    puts "outfits #{@outfits.inspect}"
  end

  def status
    @outfit = Outfit.find(params[:id])
    @outfit.update(action: Outfit.actions[params[:status]])

    redirect_to outfits_path
  end

  def update
    @outfit = Outfit.find(params[:id])
    @outfit.name = params[:name]
    @outfit.save
    redirect_to outfit_path(@outfit), notice: 'Outfit name updated successfully.'
  end

  private

  def outfits_params
    params.require(:outfit).permit(:garment_id, :shoe_id, :accessory_id, comment: [])
  end
end

app/helpers/outfits_helper.rb
module OutfitsHelper
end

app/views/outfits/_form.html.erb
<%= form_for @outfit, html: { multipart: true } do |f| %>

<%= form_for(@outfit) do |f| %>
  <% if @outfit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@outfit.errors.count, "error") %> prohibited this outfit from being put in your Armoire:</h2>

      <ul>
      <% @outfit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :garments %><br>
    <%= f.collection_select(:garment_id, current_user.garments, :id, :name, prompt: true)%><br>

    <%= f.label :shoes %><br>
    <%= f.collection_select(:shoe_id, current_user.shoes, :id, :name, prompt: true)%><br>

    <%= f.label :accessories %><br>
    <%= f.collection_select(:accessory_id, current_user.accessories, :id, :name, prompt: true)%><br>


  </div>

  <div class="field">
  </div>

  <div class="actions">
    <%= f.submit "Create Outfit" %>
  </div>
  <br>
  <% end %>
<% end %>

app/views/outfits/_outfit.html.erb
<h1>Outfit</h1>
<div class="container">
  <% Outfit.limit(1).each do |f|%>
  <div class="row">
    <div class="col-md-4">
      <p><%= f.garment.name%></p>
    </div>
    <div class="col-md-4">
      <p><%= f.shoe.name%></p>
    </div>
    <div class="col-md-4">
      <p><%= f.accessory.name%></p>
    </div>
  </div>
  <%end%>
</div>

app/views/outfits/index.html.erb
<div class="show-page">
<div class="container">

<h1>Your Armoire</h1>
<h2>Outfits</h2>
<% @outfits.each do |outfit|%>
<div class="row">
  <h3 class="center"><%=outfit.name %></h3>
  <div class="col-md-4">
    <h4><%= outfit.garment.try(:name)%></h4>
    <div class="image">
      <div>
        <img width="275" height="225" src="<%= outfit.garment.try(:image)%>">
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <h4><%= outfit.shoe.try(:name)%></h4>
    <div class="image">
      <div>
        <img width="275" height="225" src="<%= outfit.shoe.try(:image)%>">
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <h4><%= outfit.accessory.try(:name)%></h4>
    <div class="image">
      <div>
        <img width="275" height="225" src="<%= outfit.accessory.try(:image)%>">
      </div>
    </div>
  </div>
  </div>
  <div class="container">
    <div class="row">
  <% if current_user == outfit.user %>
    <%= button_to "Delete Outfit", outfit_path(outfit), method: :delete, class: "btn pull-right" %>
  <%end%>

  <% outfit.comments.each do |comment|%>
    <%= comment.comment%> By <%= comment.user.username%>

  <% if current_user == comment.user%>
    <%= link_to "Delete Comment", delete_comment_outfit_path(outfit,comment_id: comment.id), method: :delete %>
    <% end %>
  <% end %>
  <%= form_for Comment.new, url: add_comment_outfit_path(outfit) do |f|%>
    <%= f.text_area :comment %>
    <%= f.submit("Add Comment") %>

      <% end %>
    <%end%>
      </div>
    </div>

    <div class="outfit-buttons">
      <%= link_to new_outfit_path, class: "btn btn-default" do %>
      Add an Outfit!<% end %>
    </div>

</div>
</div>

app/views/outfits/new.html.erb
<div class="view_form">
  <h1>Let's Make An Outfit!</h1>
  <%= render 'form' %>

<% if current_user.garments.present? && current_user.shoes.present? && current_user.accessories.present? %>

  <%= button_to "View Your Armoire", outfits_path %>

<% else %>

  <%= button_to "Add Garment", new_garment_path %>
  <%= button_to "Add Shoe", new_shoe_path %>
  <%= button_to "Add Accessory", new_accessory_path %>

<% end %>
</div>

app/views/outfits/pending.html.erb
<div class="row">

<div class="col-md-4"></div>
<div class="col-md-4">

<% @outfits.each do |outfit|  %>
  <h4><%= outfit.name || "default_name" %></h4>

<% if current_user == outfit.user %>
  <%= button_to "Approve",status_outfit_path(outfit), method: :put, params: {status: 'approve'} %>
  <%= button_to "Reject", status_outfit_path(outfit), method: :put, params: {status: 'reject'} %>
<% end %>
<% end %>
</div>

<div class="col-md-4"></div>

app/views/outfits/random.html.erb
<h1>Random Outfits!</h1>

<div class="row">

<div class="col-md-4">
<% if @random_garment.present? %>
    <h2><%= @random_garment.try(:name)%></h2>
         <div class="image">
        <div>
          <img width="275" height="225" src="<%= @random_garment.try(:image)%>">
        </div>
      </div>
  <% else %>
    <p><%= link_to "Add Garment", new_garment_path %></p>
    </div>
    <% end %>


<div class="col-md-4">

    <h2><%= @random_shoe.try(:name)%></h2>
         <div class="image">
        <div>
          <img width="275" height="225" src="<%= @random_shoe.try(:image)%>">
        </div>
      </div>

    </div>


<div class="col-md-4">

    <h2><%= @random_accessory.try(:name)%></h2>
         <div class="image">
        <div>
          <img width="275" height="225" src="<%= @random_accessory.try(:image)%>">
        </div>
      </div>

    </div>

<%= form_for Outfit.new, html: { multipart: true } do |f| %>
<%= form_for(Outfit.new) do |f| %>
  <div class="field">
    <%= f.hidden_field :garment_id, value: @random_garment.id %><br>
    <%= f.hidden_field :shoe_id, value: @random_shoe.id %><br>
    <%= f.hidden_field :accessory_id, value: @random_accessory.id %><br>

  </div>

  <div class="field">
  </div>

  <div class="actions">
    <%= f.submit "Add to Armoire" %>
  </div>
  <% end %>
  <% end %>

  <%= link_to random_outfit_path, class: "btn btn-default", id: "pending_outfit" do %>
      <span>Get Another Random Outfit!</span>
  <% end %>


</div>

app/views/outfits/show.html.erb
<div class="view_form">
<h1>Presenting.. Your New Outfit!</h1>

<div class="container">
  <div class="row">

 <%= form_tag url_for(:controller => 'outfits', :action => 'update'), :method => 'put', remote: true do %>

     <%= text_field_tag 'name', nil, placeholder: 'Enter an outfit name...' %>
      <%= submit_tag 'Name Your Outfit' %>
  <% end %>

    <div class="col-md-4">
      <h2><%= @outfit.garment.try(:name) %></h2>
      <div class="image">
        <p>
          <img width="275" height="225" src="<%= @outfit.garment.try(:image)%>">
        </p>
      </div>
    </div>

    <div class="col-md-4">
      <h2><%= @outfit.shoe.name %></h2>
      <div class="image">
        <p>
          <img width="300" height="225" src="<%= @outfit.shoe.image%>">
        </p>
        </div>
    </div>

    <div class="col-md-4">
      <h2><%= @outfit.accessory.name %></h2>
      <div class="image">
        <p>
          <img width="300" height="225" src="<%= @outfit.accessory.image%>">
        </p>
      </div>
    </div>
  </div>
</div>
</div>
  <%= link_to pending_outfits_path, class: "btn btn-default", id: "pending_outfit" do %>
      <span>Keep or Reject This Outfit?</span>
  <% end %>


</div>