config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users

  resources :users do
    member do
      put :follow
      put :unfollow
    end
  end

  resources :outfits do
    # /outfits/pending
    collection do
      get :pending
    end

    # /outfits/:id/pending
    member do
      put :status
      post :add_comment
      delete :delete_comment
    end
  end
  resources :accessories
  resources :shoes
  resources :garments

  get 'random', to: 'outfits#random', as: 'random_outfit'
  # post 'seasonal', to: 'outfits#seasonal', as: 'seasonal_outfit'
  get 'help'    => 'home#help'
  get 'about'   => 'home#about'
  get 'contact' => 'hlome#contact'

  get 'delete/:id' => 'garments#destroy', as: 'garment_destroy'
  get 'delete_accessories/:id' => 'accessories#destroy', as: 'accessory_delete'
  get 'delete_shoes/:id' => 'shoes#destroy', as: 'shoes_delete'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         authentication_keys: [:login]

  has_many :shoes
  has_many :garments
  has_many :accessories
  has_many :outfits
  has_many :follower_friendships,
           foreign_key: 'follower_id',
           class_name: 'Friendship'

  # users that are followed by this user
  has_many :followed_users,
           through: :follower_friendships,
           source: 'followed',
           class_name: 'User'

  has_many :followed_friendships,
           foreign_key: 'followed_id',
           class_name: 'Friendship'

  # users who follow this user
  has_many :following_users,
           through: :followed_friendships,
           source: 'follower',
           class_name: 'User'

  validates :username,
            presence: true,
            uniqueness: {
              case_sensitive: false
            }

  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, multiline: true
 
  geocoded_by :current_sign_in_ip
  
  before_save :geocode_user, if: :current_sign_in_ip_changed?

  def geocode_user
    g = self.geocode
    self.latitude = g.try(:first)
    self.longitude = g.try(:last)
  end

  attr_writer :login

  def follow(another_user)
    Friendship.create(follower: self, followed: another_user)
  end

  def unfollow(another_user)
    Friendship.where(follower: self, followed: another_user).destroy_all
  end

  def is_following?(another_user)
    Friendship.where(follower: self, followed: another_user).present?
  end

  def is_followed_by?(another_user)
    Friendship.where(follower: another_user, followed: self).present?
  end

  def following_count
    follower_friendships.count
  end

  def followers_count
    followed_friendships.count
  end

  def login
    @login || username || email
  end

  def all_friends
    [followed_users.pluck(:id), following_users.pluck(:id)].uniq
  end  

  def all_outfits
     Outfit.where(:user_id => [self.id,all_friends])
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value', { value: login.downcase }]).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      conditions[:email].downcase! if conditions[:email]
      where(conditions.to_h).first
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :follow, :unfollow]

  def show
    @outfits = Outfit.where(user_id: params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user = current_user
    if @user.save
      log_in @user
      flash[:success] = 'Welcome to Armoire. Prepare to look amazing.'
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:success] = 'Your profile has been taken in!'
    else
      render 'new'
    end
  end

  def index
    @users = User.where('id != ?', current_user.id)
  end

  def follow
    current_user.follow(@user)

    respond_to do |format|
      format.js 
    end
  end

  def unfollow
    current_user.unfollow(@user)
    
    respond_to do |format|
      format.js 
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/users/_follow_unfollow.html.erb
<div class="btn-back">
    <p>Are you sure?</p>
    <button class="yes">Yes</button>
    <button class="no">No</button>
  </div>

    <% if current_user.is_following?(user) %>
      <%= link_to unfollow_user_path(user), method: :put do %>
      <div class="btn-front">Unfollow</div>
      <% end %>
        <% else %>
            <%= link_to follow_user_path(user),method: :put do %>
            <div class="btn-front">Follow</div>
            <% end %>
        <% end %>

app/views/users/_show.html.erb
<div class="container">

  <h1>User Profile: <%= @user.username %></h1>

  <div class="row">

    <div class="col-md-4">
      <h3>User:<%= @user.username %></h3>
      <h4>Email <%= @user.email  %></h3>
    </div>

    <div class="col-md-4">
      <h3>Follows: <%=@user.following_count %> Users</h3>


      <table class= "table table-hover">
        <% @user.follower_friendships.each do |follower| %>
            <tr>
              <td><%= User.find(follower.followed_id).username %></td>
            </tr>
        <% end %>
      </table>

    </div>

    <div class="col-md-4">
      <h3>Followers: <%= @user.followers_count %></h3>

      <table class= "table table-hover">
        <% @user.followed_friendships.each do |follower| %>
            <tr>
              <td><%= User.find(follower.follower_id).username %></td>
            </tr>
        <% end %>
      </table>
    </div>

  </div>

  <h2 class="center">
    <div class="row">
      <%= @user.username%>'s Outfits</h2>
  <br>
  <% @outfits.each do |outfit| %>
      <div class="col-md-4">
        <%= link_to image_tag(outfit.garment.image), class: 'img-responsive' %>
      </div>
      <div class="col-md-4">
        <%= link_to image_tag(outfit.shoe.image), class: 'img-responsive' %>
      </div>

      <div class="col-md-4">
        <%= link_to image_tag(outfit.accessory.image), class: 'img-responsive' %>
      </div>
      </div>

      <div class="container">
        <div class="row">
          <% if current_user == outfit.user %>
              <%= button_to "Delete Outfit", outfit_path(outfit), method: :delete, class: "btn pull-right" %>
          <% end %>

          <% if outfit.comments.present? %>
              <% outfit.comments.each do |comment|%>
                  <%= comment.comment%> By <%= comment.user.username%>
                  <% if current_user == comment.user%>
                      <%= link_to "Delete Comment", delete_comment_outfit_path(outfit,comment_id: comment.id), method: :delete %>
                  <% end %>
              <% end %>
          <% end %>

          <%= form_for Comment.new, url: add_comment_outfit_path(outfit) do |f|%>
              <%= f.text_area :comment %>
              <%= f.submit("Add Comment") %>
          <% end %>

  <% end %>
  </div>
  </div>

  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">

      <%= link_to users_path, class: "btn btn-default" do %>
          <i class="glyphicon glyphicon-arrow-left"></i>
      <% end %>


      <% if current_user.is_following?(@user) %>
          <%= button_to 'Unfollow', unfollow_user_path(@user),
                        method: :delete, data: {confirm: 'Are you sure?'} %>
      <% else %>
          <%= button_to 'Follow', follow_user_path(@user),
                        method: :put, data: {confirm: 'Are you sure?'} %>
      <% end %>

    </div>
    <div class="col-md-4"></div>
  </div>

app/views/users/follow.js.erb
$('#follow-unfollow-<%= @user.id %>').html("<%= j render(partial: 'follow_unfollow', locals: {user: @user} ) %>")

app/views/users/index.html.erb
<div class="user-show-page">
  <div class="container">
    <table class="table table-hover">
    <thead>
      <tr>
      <div class="container table">
          <div class="col-md-4">
          <h2 class="center">Armoire Users</h2>
          </div>

      <div class="col-md-4"></div>
          <div class="row">
      <div class="col-xs-12">
      <div class="table-responsive">
        <table summary="This table shows how to create responsive tables using Bootstrap's default functionality" class="table table-bordered table-hover">
          <thead>
            <tr>
            <th>User Name</th>
            <th>Outfits</th>
            <th>Followers</th>
            <th>Following</th>
            <th>Follow Armoire?</th>
            </tr>
          </thead>

        <tr><% @users.each do |user| %>
        <div class="table stuff">
          <td><%= link_to user.username, user %></td>
          <td><%= user.outfits.count %></td>
          <td><%= user.followers_count %></td>
          <td><%= user.following_count %></td>
          <td>
            <div class="btn-1" id="follow-unfollow-<%= user.id %>">
               <%= render partial: 'follow_unfollow', locals: {user: user} %>
            </div>
          </td>
        </div><!--closing table stuff-->
        </tr>
        <% end %>
        </tr>
        </table>
      
      </div>
      </div><!--end of .table-responsive-->
  </div>
</div>

  </div>
</div>

app/views/users/new.html.erb
<div class="view_form">
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:user, :as => user_name, :url => new_user_registration_path) do |f| %>
      <%= divise_error_messages! %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="view_form">
<div class="container">

  <h1>User Profile: <%= @user.username %></h1>

  <div class="row">

    <div class="col-md-4">
      <h3>User:<%= @user.username %></h3>
      <h4>Email <%= @user.email  %></h3>
    </div>

    <div class="col-md-4">
      <h3>Follows: <%=@user.following_count %> Users</h3>


      <table class= "table table-hover">
        <% @user.follower_friendships.each do |follower| %>
            <tr>
              <td><%= User.find(follower.followed_id).username %></td>
            </tr>
        <% end %>
      </table>

    </div>

    <div class="col-md-4">
      <h3>Followers: <%= @user.followers_count %></h3>

      <table class= "table table-hover">
        <% @user.followed_friendships.each do |follower| %>
            <tr>
              <td><%= User.find(follower.follower_id).username %></td>
            </tr>
        <% end %>
      </table>
    </div>

  </div>

  <h2 class="center">
    <div class="row">
      <%= @user.username%>'s Outfits</h2>
  <br>
  <% @outfits.each do |outfit| %>

      <div class="col-md-4">
      <div class="image">
        <img width="275" height="225"src="<%= outfit.garment.try(:image)%>">
      </div>
      </div>

      <div class="col-md-4">
        <div class="image">
       <img width="275" height="225"src="<%= outfit.shoe.try(:image)%>">
       </div>
       </div>

      <div class="col-md-4">
      <div class="image">
        <img width="275" height="225"src="<%= outfit.accessory.try(:image)%>">
        </div>
      </div>
      </div>

      <div class="container">
        <div class="row">
          <% if current_user == outfit.user %>
              <%= button_to "Delete Outfit", outfit_path(outfit), method: :delete, class: "btn pull-right" %>
          <% end %>

          <% if outfit.comments.present? %>
              <% outfit.comments.each do |comment|%>
                  <%= comment.comment%> By <%= comment.user.username%>
                  <% if current_user == comment.user%>
                      <%= link_to "Delete Comment", delete_comment_outfit_path(outfit,comment_id: comment.id), method: :delete %>
                  <% end %>
              <% end %>
          <% end %>

          <%= form_for Comment.new, url: add_comment_outfit_path(outfit) do |f|%>
              <%= f.text_area :comment %>
              <%= f.submit("Add Comment") %>
          <% end %>

  <% end %>
  </div>
  </div>

  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">

      <%= link_to users_path, class: "btn btn-default" do %>
          <i class="glyphicon glyphicon-arrow-left"></i>
      <% end %>


      <% if current_user.is_following?(@user) %>
          <%= button_to 'Unfollow', unfollow_user_path(@user),
                        method: :delete, data: {confirm: 'Are you sure?'} %>
      <% else %>
          <%= button_to 'Follow', follow_user_path(@user),
                        method: :put, data: {confirm: 'Are you sure?'} %>
      <% end %>

    </div>
    <div class="col-md-4"></div>
  </div>

app/views/users/unfollow.js.erb
$('#follow-unfollow-<%= @user.id %>').html("<%= j render(partial: 'follow_unfollow', locals: {user: @user} ) %>")