config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users

  resources :users do
    member do
      put :follow
      put :unfollow
    end
  end

  resources :outfits do
    # /outfits/pending
    collection do
      get :pending
    end

    # /outfits/:id/pending
    member do
      put :status
      post :add_comment
      delete :delete_comment
    end
  end
  resources :accessories
  resources :shoes
  resources :garments

  get 'random', to: 'outfits#random', as: 'random_outfit'
  # post 'seasonal', to: 'outfits#seasonal', as: 'seasonal_outfit'
  get 'help'    => 'home#help'
  get 'about'   => 'home#about'
  get 'contact' => 'hlome#contact'

  get 'delete/:id' => 'garments#destroy', as: 'garment_destroy'
  get 'delete_accessories/:id' => 'accessories#destroy', as: 'accessory_delete'
  get 'delete_shoes/:id' => 'shoes#destroy', as: 'shoes_delete'
end

app/models/accessory.rb
class Accessory < ActiveRecord::Base
  belongs_to :user
  has_many :outfits
  mount_uploader :image, ImageUploader

  validates :image, presence: true

  attr_accessor :image_cache

  enum season: [:summer, :fall, :winter, :spring]

 def self.random_accessory(user_id)
    Accessory.where(user_id: user_id).sample
  end
end

app/controllers/accessories_controller.rb
class AccessoriesController < ApplicationController
  def index
    @accessories = Accessory.all
  end

  def new
    @accessory = Accessory.new
  end

  def show
    @accessory = Accessory.find(params[:id])
  end

  def create
    @accessory = Accessory.new(accessory_params)
    @accessory.user_id = current_user.id
    if @accessory.save
      flash[:success] = 'Your Accessory has been added to your Armoire!'
      redirect_to @accessory
    else
      render 'new'
  end
  end

  def edit
    @accessory = Accessory.find(params[:id])
  end

  def update
    @accessory = Accessory.find(params[:id])
    @accessory.user_id = current_user.id
    if @accessory.update(accessory_params)
      flash[:success] = 'Your accessory has been updated!'
    else
      render 'new'
    end
  end

  def destroy
    @accessory = Accessory.find_by(id: params[:id])
    @accessory.destroy
    flash[:success] = "#{@accessory.name} is removed from your Armoire."
    redirect_to accessories_path
  end

  private

  def accessory_params
    params.require(:accessory).permit(:user_id, :name, :element, :style, :color, :occasion, :season, :worn, :image)
  end
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/views/accessories/_accessory.html.erb
<h2><%= link_to accessory.name, accessory %></h2>

app/views/accessories/_form.html.erb
<%= form_for @accessory, html: { multipart: true }  do |f| %>
  <% if @accessory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@accessory.errors.count, "error") %> prohibited this accessory from being put in your Armoire:</h2>

      <ul>
      <% @accessory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1></h1>
  <div class="image field">
    <%= f.label :image %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %><br>
  </div><br>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %><br>

    <%= f.label :element %><br>
    <%= f.text_area :element %><br>

    <%= f.label :style %><br>
    <%= f.text_area :style %><br>

    <%= f.label :color %><br>
    <%= f.text_area :color %><br>

    <%= f.label :occasion %><br>
    <%= f.text_area :occasion %><br>

    <%= f.label :season %><br>
    <%= f.select :season, f.object.class.seasons.keys %><br>

    <%= f.label :worn %><br>
    <%= f.check_box :worn %><br>

    <%= hidden_field_tag "accessory_id", @accessory.id %>

  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/accessories/edit.html.erb
<div class="edit_form">

<% provide(:title, "Edit accessory") %>
<h1>Alter your accessories</h1>

<div class="row">

    <%= form_for @accessory do |f| %>

    <div class="image field">
      <%= f.label :image %>
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache %><br>
    </div><br>

    <%= f.label :name %><br>
    <%= f.text_area :name %><br>

    <%= f.label :element %><br>
    <%= f.text_area :element %><br>

    <%= f.label :style %><br>
    <%= f.text_area :style %><br>

    <%= f.label :color %><br>
    <%= f.text_area :color %><br>

    <%= f.label :season %><br>
    <%= f.text_area :season %><br>

    <%= f.label :worn %><br>
    <%= f.check_box :worn %><br>

      <%= f.submit "upgrade", class: "btn btn-primary" %>
    <% end %>
  </div>
  </div>
</div>

app/views/accessories/index.html.erb
<div class="show-page">
  <h1>Your Accessories</h1>

  <div class="container ">
    <div class="row center">

      <% current_user.accessories.each do |acc| %>
        <div class="col-md-4">

          <a href="/accessories/<%=acc.id%>">
            <img src="<%=acc.image%>", img width="150" height="150">
          </a>
        </div>

      <%end%>
    </div><br>
  </div>
</div>


<div class="show_page_buttons">
  <%= link_to root_path, class: "btn btn-default" do %>
      <i class="glyphicon glyphicon-arrow-left"></i>
  <% end %>


  <%= link_to new_accessory_path, class: "btn btn-default" do %>
      <span>Add An Accessory!</span>
  <% end %>


  <%= link_to shoes_path, class: "btn btn-default" do %>
      <span>View Shoes!</span>
  <% end %>

  <%= link_to garments_path, class: "btn btn-default" do %>
      <span>View Garments!</span>
  <% end %>
</div>

app/views/accessories/new.html.erb
<div class="view_form">
  <h1>So Glamorous...The Perfect New Accessory!</h1>

  <%= render 'form' %>

  <%= link_to accessories_path, class: "btn btn-default" do %>
      <i class="glyphicon glyphicon-arrow-left"></i>
  <% end %>
</div>

app/views/accessories/show.html.erb
<div class="view_form">
<h1><%=@accessory.name.capitalize%></h1><br>

  <div class="container center">
    <div class="image" >
      <p>
        <img width="400" height="325" src="<%= @accessory.image%>">
      </p>

        <strong>Style:</strong> <%= @accessory.style %><br>
        <strong>Color:</strong> <%= @accessory.color %><br>
        <strong>Occasion:</strong> <%= @accessory.occasion %><br>
        <strong>Season:</strong> <%= @accessory.season %><br>
        <strong>Ready to wear:</strong> <%= @accessory.worn %><br>
    </div>


<%= link_to accessories_path, class: "btn btn-default" do %>
    <i class="glyphicon glyphicon-arrow-left"></i>
<% end %>

<%= link_to accessory_delete_path(@accessory), class: "btn btn-default" do %>
    <i class="glyphicon glyphicon-remove"></i>
<% end %>


<%= link_to edit_accessory_path, class: "btn btn-default" do %>
    <i class="glyphicon glyphicon-pencil"></i>
<% end %>
</div>
</div>

app/views/accessories/update.html.erb
<div class="view_form">
<h1><%=@accessory.name.capitalize %></h1><br>
  <div class="container center">
    <div class="image" >
      <p>
        <img width="400" height="325" src="<%= @accessory.image%>">
      </p>
        <strong>Style: </strong> <%= @accessory.style %><br>
        <strong>Color: </strong> <%= @accessory.color %><br>
        <strong>Occasion: </strong> <%= @accessory.occasion %><br>
        <strong>Season: </strong> <%= @accessory.season %><br>
        <strong>Ready to wear: </strong> <%= @accessory.worn %><br>
    </div>
<%= link_to accessory_path, class: "btn btn-default" do %>
    <i class="glyphicon glyphicon-arrow-left"></i>
<% end %>
<%= link_to accessory_delete_path(@accessory), class: "btn btn-default" do %>
    <i class="glyphicon glyphicon-remove"></i>
<% end %>
<%= link_to edit_accessory_path, class: "btn btn-default" do %>
    <i class="glyphicon glyphicon-pencil"></i>
<% end %>
</div>
</div>