config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users

  resources :users do
    member do
      put :follow
      put :unfollow
    end
  end

  resources :outfits do
    # /outfits/pending
    collection do
      get :pending
    end

    # /outfits/:id/pending
    member do
      put :status
      post :add_comment
      delete :delete_comment
    end
  end
  resources :accessories
  resources :shoes
  resources :garments

  get 'random', to: 'outfits#random', as: 'random_outfit'
  # post 'seasonal', to: 'outfits#seasonal', as: 'seasonal_outfit'
  get 'help'    => 'home#help'
  get 'about'   => 'home#about'
  get 'contact' => 'hlome#contact'

  get 'delete/:id' => 'garments#destroy', as: 'garment_destroy'
  get 'delete_accessories/:id' => 'accessories#destroy', as: 'accessory_delete'
  get 'delete_shoes/:id' => 'shoes#destroy', as: 'shoes_delete'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#/">&#169;Armoire 2016</a>
    <a href="http://learn-co-students.github.io/deploy-on-day-1-web-1115/">Chris², Jen, Maisie </a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://www.flatironschool.com/">Flatiron School</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="collapse navbar-collapse" id="collapse">
     <ul class="nav navbar-nav navbar-right">

       <li class="custom"><%= link_to "Home", root_path, :class => "page-scroll" %></li>

       <li class="dropdown">
         <% if user_signed_in? %>
         <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Armoire<span class="caret"></span></a>
             <ul class="dropdown-menu">
                 <li><%= link_to "Outfits", outfits_path%></li>
                 <li><%= link_to "Garments", garments_path%></li>
                 <li><%= link_to "Accessories", accessories_path%></li>
                 <li><%= link_to "Shoes", shoes_path%></li>
               </ul>
         </li>
         <li><%= link_to "Connect", users_path%></li>

           <li><%= link_to current_user.username, edit_user_registration_path, :class => "page-scroll" %></li>
           <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, :class => "page-scroll" %></li>
         <% else %>
           <li><%= link_to "Sign Up", new_user_registration_path, :class => "page-scroll" %></li>
           <li><%= link_to "Please Log In", user_session_path, :class => "page-scroll" %></li>
       <% end %>
     </ul>
   </div><!-- collapse navbar-collapse —>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="Chris Bradshaw, Chris McGuigan, Jen Abella, Maisie Athens">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-eval" => false %>
    <%= csrf_meta_tags %>

    <!-- Retina.js - Load first for faster HQ mobile images. -->
    <%# javascript_include_tag 'plugins/retina/retina.min' %>

    <!-- Default Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,100,200,300,600,500,700,800,900' rel='stylesheet' type='text/css'>
    <!-- Modern Style Fonts (Include these is you are using body.modern!) -->
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cardo:400,400italic,700' rel='stylesheet' type='text/css'>
    <!-- Vintage Style Fonts (Include these if you are using body.vintage!) -->
    <link href='https://fonts.googleapis.com/css?family=Sanchez:400italic,400' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cardo:400,400italic,700' rel='stylesheet' type='text/css'>


    <!-- IE8 support for HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<!-- Alternate Body Classes: .modern and .vintage -->



<body style="background-image: url('<%= asset_path("fashion/temp-bg.jpg") %>'); width: 110%; height: 150%;" id="page-top" class="vintage">
    <!-- Navigation -->
    <!-- Note: navbar-default and navbar-inverse are both supported with this theme. -->
    <nav class="navbar navbar-inverse navbar-fixed-top navbar-expanded">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"><%= fa_icon "fa fa-archive", text: "Your Armoire" %></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">

                  <div id="logo">
                    <%= image_tag 'fashion/armoire-logo.png', class: 'img-responsive'%>
                  </div>

                </a>

            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <%= render 'layouts/header' %>

            <!-- /.navbar-collapse -->
        </div>
    </nav>
    <!-- Instructions: Set your background image using the URL below. -->

      <%= yield %>
      <%= javascript_include_tag "application", "data-turbolinks-eval" => false %>
    </body>
</html>